#!/bin/bash

build_hostapd_config () {
	cat << EOF > $WORKDIR/hostapd.conf
beacon_int=100
ssid=${SSID}
interface=$WLAN
driver=${DRIVER}
channel=${CHANNEL}
ctrl_interface=/var/run/hostapd/ctrl
ctrl_interface_group=0
ignore_broadcast_ssid=$HIDDEN
ap_isolate=$ISOLATE_CLIENTS
noscan=$NOSCAN
EOF

	mkdir -p /var/run/hostapd/ctrl

	if [[ -n "$COUNTRY" ]]; then
	    cat << EOF >> $WORKDIR/hostapd.conf
country_code=${COUNTRY}
ieee80211d=1
EOF
	fi

	if [[ $FREQ_BAND == 2.4 ]]; then
	    echo "hw_mode=g" >> $WORKDIR/hostapd.conf
	else
	    echo "hw_mode=a" >> $WORKDIR/hostapd.conf
	fi

	if [[ -n $MAC_FILTER ]]; then
		echo "macaddr_acl=${MAC_FILTER}" >> $WORKDIR/hostapd.conf

		if [[ $MAC_FILTER == 1 ]]; then
			echo "accept_mac_file=${MAC_FILTER_FILE}" >> $WORKDIR/hostapd.conf
		fi

		if [[ $MAC_FILTER == 0 ]]; then
			echo "deny_mac_file=${MAC_FILTER_FILE}" >> $WORKDIR/hostapd.conf
		fi
	fi

	if [[ $IEEE80211N -eq 1 ]]; then
    	cat << EOF >> $WORKDIR/hostapd.conf
ieee80211n=1
ht_capab=${HT_CAPAB}
EOF
	fi

	if [[ $IEEE80211AC -eq 1 ]]; then
	    echo "ieee80211ac=1" >> $WORKDIR/hostapd.conf
	fi

	if [[ -n "$VHT_CAPAB" ]]; then
	    echo "vht_capab=${VHT_CAPAB}" >> $WORKDIR/hostapd.conf
	fi

	if [[ $IEEE80211N -eq 1 ]] || [[ $IEEE80211AC -eq 1 ]]; then
	    echo "wmm_enabled=1" >> $WORKDIR/hostapd.conf
	fi

	if [[ -n "$PASSPHRASE" ]]; then
		if [[ "$WPA_VERSION" == "2+1" || "$WPA_VERSION" == "1+2" ]]; then
			WPA_VERSION=3
		fi
	    if [[ $USE_PSK -eq 0 ]]; then
	        WPA_KEY_TYPE=passphrase
	    else
	        WPA_KEY_TYPE=psk
	    fi
	    cat << EOF >> $WORKDIR/hostapd.conf
wpa=${WPA_VERSION}
wpa_${WPA_KEY_TYPE}=${PASSPHRASE}
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP CCMP
rsn_pairwise=CCMP
EOF
	fi
}