#!/bin/bash

NOCOLOR='\033[0m'
RED='\033[0;31m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'

info () {
    echo -e "${GREEN}[I] $*${NOCOLOR}"
}

verbose () {
    echo -e "${CYAN}[V] $*${NOCOLOR}"
}

warn () {
    echo -e "${YELLOW}[W] $*${NOCOLOR}"
}

error () {
    echo -e "${RED}[E] $*${NOCOLOR}" >&2
}

fatal () {
	echo -e "${RED}[F] $*${NOCOLOR}" >&2
}
